language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm


matrix:

    allow_failures:
        - php: 7.0
        - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

notifications:
  

after_success:
    - travis_retry php vendor/bin/coveralls
    # or enable logging
    - travis_retry php vendor/bin/coveralls -v
