language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm
env:
  - DB=pgsql

services: postgresql

addons:
  postgresql: "9.3"



matrix:

    allow_failures:
        - php: 7.0
        - php: hhvm

before_script:
 - psql -c "DROP DATABASE IF EXISTS suyabay_test;" -U postgres;
 - psql -c "create database suyabay_test;" -U postgres;

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit

notifications:
  slack: andela:TeaB0c7SsX2IUwH8XR4Ehmh9
