language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm


matrix:

    allow_failures:
        - php: 7.0
        - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit

notifications:
  slack: andela:TeaB0c7SsX2IUwH8XR4Ehmh9
